### PR TITLE
Nested errors for schema - take 2

### PR DESCRIPTION
**Pull request by diogob**
# Purpose

When a domain function received nested input data, `errorMessagesForSchema` should mirror that structure so we do not lose nested error information.
This should address #24

## Technical details

This approach seems simpler than the one on #26 since it does not require any info from the schema (other than its type).
Using this code we could keep backwards compatibility or break it just to drop the schema parameter (since we can use just the generic type parameter).

### CODE REVIEW

**Comment by jansedlon** [comment]
Hi, is there possibility to support zod's discriminated unions? Discriminated unions does not extend the `AnyZodObject` so it's not possible to use it.

**Comment by diogob** [comment]
Hi @jansedlon could you open a separate issue with an example schema?

**Comment by diogob** [comment]
We could probably simplify the code quite a bit, but I want to validate the approach before investing more time.

**Review by gustavoguichard — APPROVED** [review]
LGTM

**Pull request merged**
